#ifndef HEADER_fd_src_flamenco_runtime_tests_fd_multiblock_pb_h
#define HEADER_fd_src_flamenco_runtime_tests_fd_multiblock_pb_h

#include "generated/block.pb.h"
#include "generated/context.pb.h"
#include "generated/metadata.pb.h"
#include "generated/txn.pb.h"

#define org_solana_sealevel_v1_block_context_t_msg fd_exec_test_block_context_t_msg
#define org_solana_sealevel_v1_block_effects_t_msg fd_exec_test_block_effects_t_msg
#define org_solana_sealevel_v1_fixture_metadata_t_msg fd_exec_test_fixture_metadata_t_msg
#define org_solana_sealevel_v1_sanitized_transaction_t_msg fd_exec_test_sanitized_transaction_t_msg
#define org_solana_sealevel_v1_acct_state_t_msg fd_exec_test_acct_state_t_msg
#define org_solana_sealevel_v1_feature_set_t_msg fd_exec_test_feature_set_t_msg
#define org_solana_sealevel_v1_inflation_t_msg fd_exec_test_inflation_t_msg
#define org_solana_sealevel_v1_fee_rate_governor_t_msg fd_exec_test_fee_rate_governor_t_msg

#define org_solana_sealevel_v1_block_context fd_exec_test_block_context
#define org_solana_sealevel_v1_block_context_t fd_exec_test_block_context_t
#define org_solana_sealevel_v1_block_effects fd_exec_test_block_effects
#define org_solana_sealevel_v1_block_effects_t fd_exec_test_block_effects_t
#define org_solana_sealevel_v1_fixture_metadata fd_exec_test_fixture_metadata
#define org_solana_sealevel_v1_fixture_metadata_t fd_exec_test_fixture_metadata_t
#define org_solana_sealevel_v1_sanitized_transaction fd_exec_test_sanitized_transaction
#define org_solana_sealevel_v1_sanitized_transaction_t fd_exec_test_sanitized_transaction_t
#define org_solana_sealevel_v1_acct_state fd_exec_test_acct_state
#define org_solana_sealevel_v1_acct_state_t fd_exec_test_acct_state_t
#define org_solana_sealevel_v1_feature_set fd_exec_test_feature_set
#define org_solana_sealevel_v1_feature_set_t fd_exec_test_feature_set_t
#define org_solana_sealevel_v1_inflation fd_exec_test_inflation
#define org_solana_sealevel_v1_inflation_t fd_exec_test_inflation_t
#define org_solana_sealevel_v1_fee_rate_governor fd_exec_test_fee_rate_governor
#define org_solana_sealevel_v1_fee_rate_governor_t fd_exec_test_fee_rate_governor_t

#include "generated/multiblock.pb.h"

#endif /* HEADER_fd_src_flamenco_runtime_tests_fd_multiblock_pb_h */
